# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       pulseaudio-module-cmtspeech-n9xx

# >> macros
%define pulseversion 5.0
# << macros

Summary:    Cmtspeech module for PulseAudio on N9xx
Version:    5.0.4
Release:    1
Group:      Multimedia/PulseAudio
License:    LGPLv2.1+
ExclusiveArch:  %arm
URL:        https://github.com/nemomobile/pulseaudio-module-cmtspeech-n9xx
Source0:    %{name}-%{version}.tar.gz
Source100:  pulseaudio-module-cmtspeech-n9xx.yaml
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(pulsecore) >= 5.0
BuildRequires:  pkgconfig(libmeego-common) >= 5.0.15
BuildRequires:  libcmtspeechdata-devel
BuildRequires:  libtool-ltdl-devel

%description
Cmtspeech module for PulseAudio on N9xx device.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
autoreconf -vfi
# << build pre

%reconfigure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/pulse-%{pulseversion}/modules/module-meego-cmtspeech.so
# << files
